version: "3.8"
services:
# database
  postgres-api-yugioh-connect:
    image: postgres:16-alpine
    env_file:
      - .env
    container_name: postgres-api-yugioh-connect
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - 5431:5432
    volumes:
      - ./.data/postgres:/var/lib/postgresql/data

# UI pgadmin4
  pgadmin-api-yugioh-connect:
    image: dpage/pgadmin4:8.2
    env_file:
      - .env
    container_name: pgadmin-api-yugioh-connect
    depends_on:
      - postgres-api-yugioh-connect
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIM_PASSWORD}
    ports:
      - 8080:80
    volumes:
      - ./.data/pgadmin:/var/lib/pgadmin


networks:
  default:
    name: ${NETWORK_NAME}
    external: true
