### Create duelist 
POST http://localhost:3001/duelist HTTP/1.1
content-type: application/json

{
  "name": "JP",
  "presentation": "Experienced duelist with a passion for strategic gameplay!",
  "birthDate": "24/06/11998",
  "cep":"72007040",
  "email": "duelist@example.com",
  "phone": "999999999"
}
