### Create duelist 
POST http://localhost:3001/duelist HTTP/1.1
content-type: application/json

{
  "name": "JP",
  "presentation": "Experienced duelist with a passion for strategic gameplay!",
  "birthDate": "24/06/1998",
  "cep":"72007040",
  "email": "duelist@example.com",
  "phone": "9999999999"
}

### Update duelist  
PUT  http://localhost:3001/duelist/92530245-b02a-46e5-9cc3-c7710800a5b8 HTTP/1.1
content-type: application/json

{
  "cep": "64290000"
}

### List duelist 
GET http://localhost:3001/duelist?sort=asc&&field=birthDate&&limit=10&page=1 HTTP/1.1
Content-Type: application/json


### Delete duelist
DELETE  http://localhost:3001/duelist/ec6c6447-0848-4354-b08c-19ab940edddb HTTP/1.1
content-type: application/json

### Get duelist 
GET http://localhost:3001/duelist/ec6c6447-0848-4354-b08c-19ab940edddb HTTP/1.1
content-type: application/json
