CREATE TABLE  IF NOT EXISTS duelists (
    ID VARCHAR(50) PRIMARY KEY,
    Name VARCHAR(255) NOT NULL,
    Presentation TEXT,
    BirthDate DATE NOT NULL,
    State CHAR(2) NOT NULL,
    City VARCHAR(255) NOT NULL,
    Street VARCHAR(255) NOT NULL,
    District VARCHAR(255) NOT NULL,
    Cep VARCHAR(10) NOT NULL,
    Email VARCHAR(255) NOT NULL,
    Phone VARCHAR(20) NOT NULL
);